---
title: "Exception Handling"
author: "Gary Mitchell"
date: "2026-07-27"
output: 
  html_document:
    toc: true
    toc_depth: 4
    fig_caption: TRUE
    number_sections: TRUE
    global_numbering: !number_sections
    pandoc_args: NULL
    base_format: rmarkdown::html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressMessages(library(reticulate))
```

Note: In most of the coding examples, I have intentionally omitted docstrings, just to keep the code compact. *ALL* of your functions, classes, and methods should provide docstrings.


So far, when writing our functions like EOQ below, we have *trapped* the error conditions and returned *special values* to designate which error has occurred. For example:

```{python}
import math
from numbers import Number

def eoq(D: int|float, A: int|float, v: int|float, r: float) -> float:
  
  args = ((D, A, v, r))
  
  if not all([isinstance(v, Number) for v in args]):
    # one or more arguments is non-numeric
    return -1
  
  if not all([v > 0 for v in args]):
    # one or more arguments is non-positive
    return -2

  # all arguments are valid, so calculate EOQ
  q = math.sqrt(2 * D * A / (v * r))
  
  return round(q, 2)

eoq(10000, 500, 12.95, 0.35)

```

Now, calling the eoq function with an invalid calling argument will result in either -1 or -2 being returned:

```{python}
eoq(10000, 500, 0, 0.35)
```

While this approach works, it relies on the code calling the eoq function to properly evaluate the return argument. In this case, since the result is a numeric value in all cases (i.e., whether or not an error has occurred), nothing prevents the calling code from blindly proceeding to process the return value, e.g., -2 in the example above, as if it is a valid return result.

Let's look at the same eoq method, but written to use exceptions.

```{python}
def eoq(D: int | float, A: int | float, v: int | float, r: float) -> float:

  args = ((D, A, v, r))

  # Use exceptions to gracefully handle anticipated errors
  try:
      q = math.sqrt(2 * D * A / (v * r))
  except (ZeroDivisionError, ValueError) as e:
      return -2
  except TypeError as e:
      return -1

  return round(q, 2)


eoq(10000, 500, 12.95, 0.35)
```

```{python}
eoq(10000, 500, 'twelve ninety-five', 0.35)
```

The code above shows how we would write *the same* code using Exceptions rather than if statements. Unlike our original code, we didn't write any *up front* validation code. Instead, we simply *try* our calculation and then added *except* blocks to *catch* certain types of errors that we anticipate could be generated by the calculation.

Our first except statement catches either a ZeroDivisionError or a ValueError. The first will occur if either v or r is zero, while the second will occur if the radicand is negative. The second except catches only TypeErrors, which would occur if a non-numeric value is specified for any of the four calling arguments.

*Any other exceptions will be ignored*; exceptions not *caught* by an except will be propagated.

### How exceptions work

The mechansims for handling exceptions is built into Python. In fact, when you have experienced type errors, or other errors, when running your Python code, it is because Python encountered an *unhandled* or *uncaught* exception; whenever Python encounters an invalid condition during execution, it *raises* the appropriate exception. By raising different types of exceptions, e.g., TypeError, ZeroDivisionError, etc., Python gives us information about the specific cause of the error that caused our program to terminate.

When an exception is *raised*, Python looks for a suitable *Except* statement to *catch* the error. If one is found, then execution is transferred to the code in the except block so that the error can be handled *gracefully*. If none is found, then the exception is *propagated*. 

Propagating an error means *unwinding* the call stack. For example, if the error occurred *inside* our eoq function, that means that code outside of the function called eoq which resulted in an exception *inside* of eoq. If no *except* is found in the eoq function, then the call stack is unwound to the code which originally invoked eoq and Python looks to see if that code was embedded in a try/except block. If so, and the block catches the type of exception raised, execution is transferred to the code in the except block and the error is handled gracefully. If no except catches the error, then propagation continues, until the call stack is completely unwound, i.e., the top-level code did not catch the exception. In this case, Python terminates the program and outputs information about the exception that caused the program to terminate.

### A propagation example

Consider the eoq function defined below. It contains no validation *or* exception handling. As a result, the exception will be propagated up to the *calling* code, which then simply prints the exception and terminates

```{python}
def eoq(D: int | float, A: int | float, v: int | float, r: float) -> float:

  args = ((D, A, v, r))

  q = math.sqrt(2 * D * A / (v * r))
  
  return round(q, 2)

# Catch any anticipated exceptions that occur in eoq

try:
  eoq(10000, 500, 0, 0.35)
except Exception as e:
  # catch ANY exception and print
  print(e)
```

```{python}
try:
  eoq(10000, 500, 'twelve ninety-five', 0.35)
except Exception as e:
  # catch ANY exception and print
  print(e)
```

### try-except-finally

There are 3 keywords that can be used with exception handling:

- try - denotes the beginning of a *try block*. Any exceptions thrown following the try (and before an except or finally) will be catchable by an except

- except - *catches* thrown exceptions

- finally - regardless of whether an exception is thrown, execution transfers to the finally (either after the code in the try succeeds or after the code in an except completes).

#### try

The try statement is simple, as shown in the examples above. There's not much more to say, other than to emphasize that the try marks the beginning of a code segment for which excepts will follow.

#### except

The syntax for an except is as follows:

```{python, eval=FALSE}
except [Type(s)] [as name]:
```

When specifying a single error type, simply specify the class name of the exception (e.g., ZeroDivisionError); multiple error types must be specified as a tuple of types, e.g., (ValueError, ZeroDivisionError).

You can specify multiple except clauses (as shown in the eoq example above), to provide exception-specific handling.

The following two except clauses are equivalent:

```{python, eval=FALSE}
except:
  
except Exceptions:
```

In both cases, exceptions of any/all types are caught.

**I strongly discourage you from using blanket except clauses** (i.e., clauses where no specific exception type(s) is(are) specified). Catching exceptions should be intentional. You should understand the nature of the code you are executing and the types of exceptions that could be expected (and therefore caught and handled gracefully). Any exceptions that you could not anticipate represent serious errors and should be allowed to propagate, unwind the call stack, and cause program termination.

The use of `python as name` clause, e.g., `python except TypeError as e`, allows you to catch the exception and evaluate its contents (some Exceptions may contain debugging information to aid in problem resolution). You may also modify the cauth exception through the reference.

#### finally

The finally clause allows you to add cleanup code (i.e., code that you need to execute to wrap things up, e.g., closing files, saving data). The finally will execute regardless of whether an exception occurs:

- If no exception occurs, the finally clause executes following the end of the code in the try
- If an exception occurs, the finally clause executes after the except clause completes.

In the following, no exception occurs, so we'll see the calculated result for $Q^*$, followed by the indication that the finally clause was executed.

```{python}
try:
    print(f'Q* = {eoq(10000, 500, 12.95, 0.35)}')
except TypeError as e:
    # catch ANY exception and print
    print('One or more of the calling arguments is non-numeric')
except (ZeroDivisionError, ValueError) as e:
    print('One or more of the calling arguments is invalid (i.e., less than or equal to 0)')
finally:
    print('in the finally')

```

However, in the code below, a ZeroDivisionError occurs as the result of v=0, so we'll see the printed error message followed by the indication that the finally clause was executed.

```{python}
try:
    print(f'Q* = {eoq(10000, 500, 0, 0.35)}')
except TypeError as e:
    # catch ANY exception and print
    print('One or more of the calling arguments is non-numeric')
except (ZeroDivisionError, ValueError) as e:
    print('One or more of the calling arguments is invalid (i.e., less than or equal to 0)')
finally:
    print('in the finally')

```

### raise

The *raise* keyword allows you to *throw* an exception:

```{python}

try:
  raise TypeError
except ZeroDivisionError as e:
  print('divide by zero')
except TypeError as e:
  print('non-numeric calling argument type')

```

Why would we ever want to raise an exception? There are two good use cases:

- We want to catch the exception and do some handling, but then we want the exception to propagate anyway. This will result in the stack unwinding and the application terminating with the error (unless some code further down in the stack catches and handles the exception)
- We want to throw our own exceptions (I'll illustrate this shortly).

The following example illustrates using raise to propagate the error:

```{python}
def eoq(D: int | float, A: int | float, v: int | float, r: float) -> float:

  args = ((D, A, v, r))

  # Use exceptions to gracefully handle anticipated errors
  try:
      q = math.sqrt(2 * D * A / (v * r))
  except (ZeroDivisionError, ValueError) as e:
      print(f'eoq caught {type(e)} exception and propagated it')
      raise e
  except TypeError as e:
      print(f'eoq caught {type(e)} exception and propagated it')
      raise e

  return round(q, 2)


try:
  eoq(10000, 500, 12.95, 0.35)
except TypeError as e:
  print(e)
except (ValueError, ZeroDivisionError) as e:
  print(e)
  
```

### Defining your own exceptions

There are a variety of reasons for defining your own exception types, including:

- Providing additional information about the error in the Exception
- Adding new types of exceptions.

The following example illustrates a couple of important concepts:

- Preventing construction of an invalid object
- Defining a new Exception that provides additional information.

To define a new exception, we simply derive a class from Exception:

```{python}

class EOQException(Exception):

    def __init__(self, D, A, v, r):
        super().__init__()
        self.D = D
        self.A = A
        self.v = v
        self.r = r

    def __str__(self):
        msg = f'One or more of the calling arguments was invalid:\n{self.D=}\n{self.A=}\n{self.v=}\n{self.r=}'
        
        
        return msg


```

In our new exception's constructor, we first call the base class (Exception) constructor, and then assign the values of the calling arguments (EOQ's parameters) to internal variables so that we can evaluate them in the exception. We've also defined an *str* method to make our exception output a little nicer.

Next, we'll define a new EOQ class.

```{python}

class Eoq():

    def __init__(self, D: int|float, A: int|float, v: int|float, r: float):
        if all([isinstance(x, Number) and x > 0 for x in (D, A, v, r)]):
            # all arguments are valid - assign to private member variables
            self._D = D
            self._A = A
            self._v = v
            self._r = r

            self._q = math.sqrt(2 * D * A / (v * r))
        else:
            raise EOQException(D, A, v, r)

    def __str__(self):
        return f'Q* = {self._q}'

```

This is a simple class. What's important about this example is the constructor. Notice that we verify that *all* calling arguments are numeric and greater than or equal to zero. When they are, we assign their values to private member variables (to retain them), and then calculate and store the EOQ as _q.

However, what's *most* interesting is what we do when one or more of the calling arguments is *invalid*; we raise an EOQException. **By raising the exception here, _construction of the object is never completed_.** In other words, we prevent the object from ever being created. From an OOP perspective, that's the ideal: invalid objects never get constructed, so if we have an object, we know it's valid.

Python maintains a directory of all objects. *dir()* returns a list of all objects in the current execution frame, so we can use it to verify whether or not an object was created. Here's an example of using dir():

```{python}
print(dir())
```

Let's see our new classes in action. The following will construct a valid EOQ object, so *'good_item'* should be in the dir() collection:

```{python}
try:
    good_item = Eoq(10000, 500, 12.95, 0.35)

except EOQException as e:
    print(e)
    
print(f'Object was created: {"good_item" in dir()}')
```

We see that *good_item* was created. Now, let's try to construct the EOQ with an error:

```{python}
try:
    bad_item = Eoq(10000, 500, 0, 0.35)
except EOQException as e:
    print(e)

print(f'Object was created: {"bad_item" in dir()}')
```

Here, we see that *bad_item* was not created (it was not found in dir()). By raising the exception in the constructor, we prevented the object from being created.'


