# Regular Expressions
**Gary Mitchell**

**4/1/2021**

Regular expressions are an extremely powerful feature for performing string search and replace operations.
They are supported by many environments (e.g. Unix) and programming languages (Java, Python, R, Perl,
C/C++, etc.) and an understanding of how to use regular expressions can lead to huge time savings
and potentially significant execution efficiencies.

Regular expression support is built-in to Python, but you must import the *re* package to utilize
regular expressions in your code.

In [1]:
import re

## Regular expression syntax

Because regular expressions (regex) are so powerful and flexible, the regex syntax can sometimes be quite challenging.
However, simple regular expressions can be quite easy to use. We can perform a regular expression search using:

    match = re.search(pattern, string)

After the execution, the match variable will contain a *Match* object which we can use to evaluate the results of our
match. *Match* objects can be evaluated as booleans, so we can easily see if our search found a match.

For example, we can search for an 'a' in the word 'plantano' as follows:

In [2]:
match = re.search('a', 'platano')
print(bool(match))

True


We can test for a match in our code using a simple conditional. If we *only* want to know if there's a match (i.e. we
do not need any other information about the match), then we could use the following:

In [3]:
if re.search('a', 'platano'):
    # do stuff when a match is found
    print('match')
else:
    # do stuff when no match is found
    print('no match')

match


However, regular expressions allow us to do more. For example, the match object contains the starting and ending
positions of the pattern match. For example:

In [4]:
match = re.search('a', 'platano')
if match:
    print(f'match starts at: {match.start()}')
    print(f'match ends at: {match.end()}')
else:
    print('no match found')

match starts at: 2
match ends at: 3


Finding 'an' instead of 'a' yields a sligthly more interesting example.

In [5]:
match = re.search('an', 'platano')

if match:
    print(f'match starts at: {match.start()}')
    print(f'match ends at: {match.end()}')
else:
    print('no match found')

match starts at: 4
match ends at: 6


In this example, because we are now searching for 'an' instead of 'a', we no longer find a match at position 2.
Instead, we match on the 'an' that begins in position 4.


## Compiled regular expressions.

So far, we have been using interpretted regular expressions. These are fine when we are executing the search only a few
times in the code. However, if we are searching repeatedly for a single pattern, we may want to use a *compiled*
regular expression. Doing so is quite straightforward:

In [26]:
# compile the regular expression
pat = re.compile('an')

# search using the compiled regular expression
match = pat.search('platano')

if match:
    print(f'match starts at: {match.start()}')
    print(f'match ends at: {match.end()}')
else:
    print('no match found')

match starts at: 4
match ends at: 6


Note that the results are identical to those of the interpretted search. However, when using the compiled regular
expression, the work to interpret the search pattern must be performed only once. All subsequent searches using
the compiled pattern save that initial step.

## Searching multiple words at once

We can also search lists of strings quite easily using a list comprehension. In the code below, we see that a regex
search for the letter 'a' finds a match on apple, but not for'moon'.

In [7]:
words = ['apple', 'moon']

matches = [bool(re.search('a', w)) for w in words]

matches

[True, False]

Using the comprehension will produce a list of results. In the example above, I converted the *Match* object's
True/False value for each word in the list. This provided a nice neat list of which words matched and which
words did not match.


## More powerful regular expressions

Regular expression searches, unless specified otherwise, will match on any *hit* within the string. In the following,
our search for 'o' matches 'organ' and 'balloon' but not 'apple'.

In [8]:
words = ['apple', 'organ', 'balloon']

matches = [bool(re.search('o', w)) for w in words]

matches

[False, True, True]

### Regex wildcards
However, regex searches support a great deal of complexity, enabling wildcard matches, specifying that matches must
occur at the beginning or ending of a string, etc. In a regex search expression, a dot ('.') will match on any single
character. In the following, 'a.' matches on 'apple', 'asterisk', 'orange', and 'apricot' because, in all cases,
a letter 'a' is found and followed by an additional character. However, 'comma' does *not* match because, while
a letter 'a' is found, it is not followed by a letter.

In [9]:
words = ['apple', 'asterisk', 'orange', 'apricot', 'comma']

matches = [bool(re.search('a.', w)) for w in words]

matches

[True, True, True, True, False]

The asterisk ('\*') can be used to represent 0 or more letters. So, rerunning our search from above with 'a\*'
instead of 'a.' will match all five words, because we have indicated that the a character *following* the 'a'
is optional.

In [10]:
matches = [bool(re.search('a*', w)) for w in words]

matches


[True, True, True, True, True]

### Regex sets
We can use *sets* to provide additional flexibility/generality in our matches. For example, let's say that
we want to find words with an 'a' immediately followed by a 'p' or an 's' (but not other characters). We
could use the following:

In [11]:
matches = [bool(re.search('a[ps]', w)) for w in words]

words
matches



[True, True, False, True, False]

Here we matched 'apple', 'asterisk', and 'apricot', but did not match 'orange' or 'comma' because although 'orange' and
'comma' contain 'a', the 'a' in these words is not followed by either 'p' or 's'.

### Forcing matches at the beginning or end of a string

We use the caret ('^') to indicate that a match must occur at the beginning of a string and a dollar sign ('$')
to form a match only at the end of a string. For example, to find words that end with the letter 'a' we would use:

In [12]:
matches = [bool(re.search('a$', w)) for w in words]

print(words)
matches


['apple', 'asterisk', 'orange', 'apricot', 'comma']


[False, False, False, False, True]

In the above, we matched only 'comma'. Although the other 4 words contained the letter 'a', none of them *ended* with
the letter 'a'.

Similarly, we could find only those words that *begin* with 'a':

In [13]:
matches = [bool(re.search('^a', w)) for w in words]

print(words)
matches


['apple', 'asterisk', 'orange', 'apricot', 'comma']


[True, True, False, True, False]

## Learning the basics

The best way to learn how to use regular expressions is to *play* around and discover what works. Additionally, there
are good sources of introductory and advanced usage descriptions and exampes available on the Internet. Here are a
couple of *official* sources:

- Introduction to Regular Expressions: [Regular Expression HOWTO](https://docs.python.org/3/howto/regex.html#regex-howto)

- re Module documentation: [re - Regular Expression Operations](https://docs.python.org/3/library/re.html)


# Extracting *fields* embedded in a string

Symbolic names can be used to facilitate accessing match groups (we discuss match groups below):

    (?P<name>...)

The utilization is similar to using regular groups (e.g. parenthesis), but the matched substring can be accessed
by *name*. The following example shows how to extract the latitude and longitude from a coordinate string with
format (lat, lon).

The pattern used below **requires** an opening '(' as the first character and a closing ')' as the last character. lat and lon
must be separated by a comma (',') and *optional* spaces. The explanation of the pattern below is quite involved. To
oversimplify a bit for a basic understanding:

- This pattern contains two match groups
    - One group will be named 'lat'
    - One group will be named 'lon'
- Each value (lat or lon) must contain:
    - optional negative sign
    - one or more digits (i.e. numeric characters)
    - an optional decimal point optionally followed by zero or more digits

In [14]:
# compiling the re pattern allows for efficient reuse
pat = re.compile(r'^\(((?P<lat>-*\d+\.*\d*), *(?P<lon>-*\d+\.*\d*))\)$')

rslt = pat.search( r'(45.7, -122.4)')

if rslt:

	# print(type(rslt))
    #
	# print(rslt)
	print(f"lat: {rslt.group('lat')}")
	print(f"lon: {rslt.group('lon')}")

else:
	print('no match')

lat: 45.7
lon: -122.4


We obtain the *value* of the group using the *group* method of the Match object. The names we assigned the group,
'lat' and 'lon', will be the keys for accessing the results. In this case, we see that our regex search correctly
extracted the values of the latitude (45.7) and longitude (-122.4). Using a regex isn't the *only* way to extract
the latitude and longitude from the coordinate string, but it's a nice and efficient way to do so.

## Match groups explained

For extensive patterns involving multiple matches within a string, we can use *match groups*. In the lat/lon example
above, we used a match group for each of 'lat' and 'lon'. More specifically, we used *symbolic names* to facilitate
our retrieving the results by group and improving program readability.

The example below illustrates the use of match groups
in a simpler pattern than in the lat/lon example. Here, we make the pattern 'oo' a group by enclosing it with parentheses, e.g. '(oo)'. Sets of
parenthesis identify groups within a pattern.

We perform the search as usual with our modified pattern and obtain a Match object as a result. However, this Match
object will include a result for each match group in the pattern. The groups() method returns the collection of
match groups.

In [15]:
match = re.search('(oo)', 'monsoon')
print(match.groups())

('oo',)


Once we have a match group, we can obtain detailed information for the matched pattern:

    - The string that matched the pattern
    - The starting index of the match
    - The ending index of the match (actually, the index after the last character matched)

Whereas the groups() returns a collection of *all* match groups (only one in this case), we can access a specific group
directly using the group(index) method:

In [16]:
# need to make pattern a group using () to get positions

print(match.group(0))
print(match.start(0))
print(match.end(0))


oo
4
6


## Counting letters

Regular expressions can be used to find strings matching requirements on numbers of letters, etc.
Here's an example of determining whether the words have 6 letters. The pattern indicates that there must be
six lower case letters at the beginning of the line/string (^) and nothing following the last character
but the line termination ($):

In [17]:
pat = re.compile(r'^[a-z]{6}$')

def test(str):
	rslt = pat.search(str)
	if rslt:
		return(True)
	else:
		return(False)

words = ['george', 'sam', 'stephen', 'caitie']

for w in words:
    print(f'{w}: {test(w)}')

george: True
sam: False
stephen: False
caitie: True


Technically, this is different than checking the length of the strings. Given a string 'abc123', the len function would
return 6, reflecting the length of the string in characters (not specifically *letters*). However, the regex search
above would *not* match on 'abc123' because three of the characters are digits, rather than a lower case letter between
'a' and 'z'. So, depending on what we know about the data a priori, and the intent of our analysis, we decide on which
approach yields the appropriate result.

Ultimately, if we know all characters in a string are letters, then using len(...) will
suffice; actually when we know all characters are letters, using len(...) would be the best choice because it will
more efficiently answer the question of whether the string has 6 characters than the regex search. However, if we
need to simulataneously determine that the string has a length of 6 and contains only letters 'a' through 'z' then
the regex search would be the right choice.

We can then easily count the number of words having 6 letters:

In [18]:
rslts = [test(x) for x in words]
print(rslts)

print(sum(rslts))


[True, False, False, True]
2


## Challenging matches

Some matches can be quite challenging. For example, testing whether a word contains a double-o
sequence seems straightforward, but can be tricky:

In [19]:
oowords = ['son', 'moon']

for w in oowords:
    rslt = re.search('oo', w)
    if rslt:
        print(f'{w}: contains oo')
    else:
        print(f'{w}: no match')

son: no match
moon: contains oo


The problem is that some words we *don't* want to match will match. For example, consider
the following search. YoooHooo will match but contains 3, not 2 consecutive o's:

In [20]:
oowords = ['son', 'moon', 'yooohooo']

for w in oowords:
    rslt = re.search('oo', w)
    if rslt:
        print(f'{w}: contains oo')
    else:
        print(f'{w}: no match')

son: no match
moon: contains oo
yooohooo: contains oo


To resolve this problem, we need a pattern that will match exactly two consecutive o's. We do this
using look behind and look ahead patterns. The look

### Look behind patterns
    - (?<=) - positive look behind (the sequence preceding must match pattern )
    - (?!=.) - negative look behind (the pattern preceding must not match pattern)

### Look ahead patterns
    - (?=) - positive look ahead (the sequence following must match pattern )
    - (?!.) - negative look ahead (the pattern following must not match pattern)

Here's an example using negative look behind and look ahead to ensure that we match on only two
consecutive o's:

In [21]:
oowords = ['son', 'moon', 'yooohooo']

for w in oowords:
    rslt = re.search(r'(?<!o)o{2}(?!o)', w)
    if rslt:
        print(f'{w}: contains oo')
    else:
        print(f'{w}: no match')


son: no match
moon: contains oo
yooohooo: no match


This pattern literaly says to search for:

- Two consecutive o's - o{2}
    - Where
        - the character preceding the match is not an 'o' - (?<!o)
        - the character following the match is not an 'o' - (?!o)

We used an **r-string** (or *raw* string) in the example above. In standard Python strings, certain sequences represent *escape characters*
that are interpretted in a special way. For example, '\n' represents a line feed. In the following example, we see
what happens with the embedded '\n' when a string is printed:

In [22]:
print('This is line 1...\nand line 2')

This is line 1...
and line 2


If we want a standard excape sequence like '\n' to be treated like normal characcters, we can *escape* the escape
sequence:

In [23]:
print('This is line 1...\\nand line 2')

This is line 1...\nand line 2


However, escaped escape sequences can start to make a regex pattern pretty ugly (and incomprehensible?). But Python
completely ignores any typical escape sequences in r-strings, treating every character as just a
standard character. This is helpful when writing regex patterns because we don't have to worry about whether a
regex metacharacter will be interpretted as an escape sequence. Here we see what happens with the same print
statement but using an r-string:

In [24]:
print(r'This is line 1...\nand line 2')

This is line 1...\nand line 2


For simple regex patterns, there's generally no need to use r-strings. However, for more complex regex patterns it
is a good idea to automatically use r-strings to simplify the pattern specification (this way we can avoid the need
to *escape* the escape sequence).